import = [
    "~/.config/alacritty/themes/kanagawa_wave.toml"
]

[font]
size = 13.0
offset = { x = 0, y = 4 }

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[window]
decorations = "None"

[window.padding]
x = 10
y = 10
