import = [
    "~/.config/alacritty/themes/nord.toml"
]

[font]
size = 12.0
offset = { x = 0, y = 4 }
glyph_offset = { x = 0, y = 2 }

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "None"

[window.padding]
x = 10
y = 10
