[[language]]
name = "rust"
rulers = [100]

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true
