# Kanagawa
# set $base00 #1f1f28
# set $base01 #16161d
# set $base02 #223249
# set $base03 #54546d
# set $base04 #727169
# set $base05 #dcd7ba
# set $base06 #c8c093
# set $base07 #717c7c
# set $base08 #c34043
# set $base09 #ffa066
# set $base0A #c0a36e
# set $base0B #76946a
# set $base0C #6a9589
# set $base0D #7e9cd8
# set $base0E #957fb8
# set $base0F #d27e99

# base02
idle_bg = "#223249"
# base05
idle_fg = "#dcd7ba"
# base0D
info_bg = "#7e9cd8"
# base00
info_fg = "#1f1f28"
# base0B
good_bg = "#76946a"
# base00
good_fg = "#1f1f28"
# base0A
warning_bg = "#c0a36e"
# base00
warning_fg = "#1f1f28"
# base08
critical_bg = "#c34043"
# base00
critical_fg = "#1f1f28"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
